version: '3'

services:
  apprtc-server:
    image: piasy/apprtc-server
    container_name: apprtc-server
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
      - "8089:8089"
      - "3478:3478"
      - "3478:3478/udp"
      - "3033:3033"
    expose:
      - "59000-65000"
    volumes:
      - ./config:/apprtc_configs
      - /etc/localtime:/etc/localtime

  apprtc-web:
    depends_on:
      - apprtc-server
    image: nginx:1.15.12-alpine
    container_name: apprtc-web
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "441:441"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - /cert:/cert
      - /etc/localtime:/etc/localtime